export const APP_ROUTES = [
  "/(auth)/(tabs)",
  "/(auth)/(tabs)/care",
  "/(auth)/(tabs)/routines",
  "/(auth)/(tabs)/progress",
  "/(auth)/(tabs)/profile",
  "/(auth)/intake",
  "/(auth)/intake/camera",
  "/(auth)/intake/symptom-log",
  "/(auth)/intake/pre-visit",
  "/(auth)/intake/review",
  "/(auth)/settings",
  "/(auth)/notifications",
  "/(auth)/consent",
  "/(auth)/label-scan",
  "/(auth)/timeline",
  "/(auth)/interventions",
  "/(auth)/onboarding/skin-brief",
  "/(auth)/onboarding/preferences",
  "/(auth)/onboarding/goal-journey",
  "/weekly-reveal",
] as const;
